name: Check

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  nix:
    name: Nix configuration
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Check flake
        working-directory: nix
        run: nix flake check

      - name: Check Oxfmt formatting
        run: nix run ./nix#oxfmt -- --check .

      - name: Check Justfile formatting
        run: nix run ./nix#just -- --justfile justfile --fmt --check

      - name: Build LCDEV0215
        working-directory: nix
        run: nix build .#darwinConfigurations.LCDEV0215.system --no-link
